/* CREATE USER */

CREATE USER 'user'@'%' IDENTIFIED BY '123';

/* PRIVILGES FOR ROOT AND USER FOR ALL IP ADRESS */ 
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'password';

CREATE DATABASE wordpress;
FLUSH PRIVILEGES; 

